CREATE TABLE estados_reserva
(
    id_estado SERIAL PRIMARY KEY,

    nombre VARCHAR(50) NOT NULL UNIQUE,

    activo BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);