#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

use Core\Config;
use Core\Database;

Config::load(__DIR__);

$command = $argv[1] ?? null;

switch ($command) {

    case 'create:admin':
        require __DIR__ . '/src/console/create_admin.php';
        break;

    case 'reservas:recordatorios':
        require __DIR__ . '/src/console/enviar_recordatorios.php';
        break;

    case 'reservas:finalizar':
        require __DIR__ . '/src/console/finalizar_reservas.php';
        break;

    default:
        echo PHP_EOL;
        echo "ReservaLab Console\n";
        echo "==================\n\n";
        echo "Comandos disponibles:\n\n";
        echo "  php console create:admin\n";
        echo "  php console reservas:recordatorios [minutos=5]\n";
        echo "  php console reservas:finalizar\n\n";
        break;
}